application: destiny-heliosphere
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
  - name: webapp2
    version: latest
  - name: jinja2
    version: latest

handlers:
  - url: /static
    static_dir: static

  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  - url: /bot/.*
    script: web.app
    login: optional

  - url: /.*
    script: web.app
    login: required

  - url: /admin/.*
    script: web.app
    login: admin
